### ISSUE TITLE
Add Project and Account Switcher Component

### ISSUE THREAD

**Issue by camwest** [Autodesk/orion-ui#215]
Possible JSX based on designs: https://wiki.autodesk.com/pages/viewpage.action?pageId=315334705

Default Example
```jsx
<GlobalNav>
    <TopNav>
      <ProjectAccountSwitcher
        activeLabel={activeProject.label}
        activeType="project"
        activeImage={activeProject.image}
        open={this.state.accountSwitcherOpen}
        onClick={this.openAccountSwitcher}
        onClickOutside={this.closeAccountSwitcher}
      >
        {projects.map((project) => { return <Project image={project.image} label={project.label} /> })}
        {accounts.map((account) => { return <Account image={account.image} label={account.label} /> })}
      </ProjectAccountSwitcher>
  </TopNav>
</GlobalNav>
```

Assumptions:

* Switcher has a show and hide method of some sort
* Switcher has a showCaret hideCaret method
* Search triggers on onChange event when the user types into the input
* Switcher triggers on onClear event when the user clicks the clear button if a search string is input
* Search has a setValue method to change the input text
* hig.web is not responsible for managing search visibility since it is derived from the length of the number of items (ie is stateful)
* Filtering is done onChange and it'll be handled on the Application side

---

**TODO**
- [ ] Add PropTypes
- [ ] Add docgenInfo
- [ ] Add unit test coverage
- [ ] Add to playground
- [ ] Add to storybook
  - [ ] With code sample
  - [ ] With props table
- [ ] Canary build on NPM
- [ ] Has PO sign off

**Comment by camwest** [comment]
@recyclerobot can you give feedback on these assumptions?

cc @nfiniteset

**Comment by unitedempire** [comment]
@nfiniteset Issue #237 is a clone of this. I would just keep one.

**Comment by aneyzberg** [comment]
completed by #247

**Comment by aneyzberg** [comment]
Here is the canary build tag - 1.0.3-alpha.c765a046
