### ISSUE TITLE
Add Profile Image to TopNav

### ISSUE THREAD

**Issue by camwest** [Autodesk/orion-ui#216]
```jsx
<GlobalNav>
  <Container>
    <TopNav>
      <Profile 
        image="someUrl" 
        onProfileImageClick={Function}
      />
    </TopNav>
  </Container>
</GlobalNav>
```

* Profile has methods to set image
* Profile has events for onClick on the icon

---

**TODO**
- [x] Add PropTypes
- [x] Add docgenInfo
- [x] Add unit test coverage
- [x] Add to playground
- [x] Add to storybook
  - [x] With code sample
  - [x] With props table
- [x] Canary build on NPM
- [x] Has PO sign off

**Comment by recyclerobot** [comment]
would rename `onIconClick` to `onProfileImageClick`, looks good otherwise!

**Comment by aneyzberg** [comment]
@unitedempire This story is ready for review. Here is the build tag - 1.0.3-alpha.fe16a33f

**Comment by unitedempire** [comment]
@aneyzberg Thank I will check it out, also in the future, can you also tag the issue # to the PR

**Comment by unitedempire** [comment]
Related to PR #227

**Comment by aneyzberg** [comment]
Yes of course. Sorry about that.
