### ISSUE TITLE
Add Profile Flyout to TopNav

### ISSUE THREAD

**Issue by nfiniteset** [Autodesk/orion-ui#220]
```jsx
<GlobalNav>
    <TopNav>
    <Profile 
        open={true} 
        image="someUrl" 
        onProfileImageClick={Function} 
        name="Really Really Really long Name" 
        email="some-email@example.com" 
        signOutLabel="Sign out" 
        onSignOutClick={Function} 
        profileSettingsLabel="Profile Settings" 
        profileSettingsLink="http://example.com" 
/>
  </TopNav>
</GlobalNav>
```

* Profile has a open/close method
* Profile has methods to set image, name, email, signoutLabel, profileSettingsLabel, and profileSettingsLink
* Profile has events for onClick on the icon and clicking on the sign out button

---

**TODO**
- [x] Rework necessary stuff since getting rid of Container
- [x] Add PropTypes
- [x] Add docgenInfo
- [x] Add unit test coverage -- WIP
- [x] Add to playground
- [x] Add to storybook
  - [x] With code sample
  - [x] With props table
- [x] Canary build on NPM -- send Ahmed the version no.
- [x] Has PO sign off

**Comment by shannonwells** [comment]
#239  PR up for review
