### ISSUE TITLE
Add ProjectAccountSwitcher to TopNav

### ISSUE THREAD

**Issue by nfiniteset** [Autodesk/orion-ui#237]
```jsx
<GlobalNav>
    <TopNav>
      <ProjectAccountSwitcher
        activeLabel={activeProject.label}
        activeType="project"
        activeImage={activeProject.image}
        open={true}
        onClick={this.openAccountSwitcher}
        onClickOutside={this.closeAccountSwitcher}
      >
        {projects.map((project) => { return <Project image={project.image} label={project.label} /> })}
        {accounts.map((project) => { return <Account image={account.image} label={account.label} /> })}
      </ProjectAccountSwitcher>
  </TopNav>
</GlobalNav>
```

---

**TODO**
- [ ] Add PropTypes
-  [ ] Add docgenInfo
- [ ] Add unit test coverage
- [ ] Add to playground
- [ ] Add to storybook
  - [ ] With code sample
  - [ ] With props table
- [ ] Canary build on NPM
- [ ] Has PO sign off
