### ISSUE TITLE
Integrate TopNav Search

### ISSUE THREAD

**Issue by recyclerobot** [Autodesk/orion-ui#246]
As an app developer
I can enable searching my app's content
so my users can find the content they need

```jsx
<TopNav>
  <Search placeholder="Search for things" query={this.state.query} onInput={this.applyQuery} onClearIconClick={this.clear} />
</TopNav>
```

```js
Search.propTypes = {
  query: PropTypes.string,
  placeholder: PropTypes.string,
  onInput: PropTypes.func,
  onClearIconClick: PropTypes.func,
}
```

---

### Developer notes
- Clicking the clear icon should clear the input
- Typing into the search field should update the field.
- Props should override any internal state

---

**TODO**
- [ ] Add PropTypes
- [ ] Add docgenInfo
- [ ] Add unit test coverage
- [ ] Add to playground
- [ ] Add to storybook
  - [ ] With code sample
  - [ ] With props table
- [ ] Canary build on NPM
- [ ] Has PO sign off
