### ISSUE TITLE
Add Button

### ISSUE THREAD

**Issue by unitedempire** [Autodesk/orion-ui#273]
```
As a developer
I want to add Buttons to my application
So that our users are able to interact with our application
```

As an app developer
use the Profile without configuration
so I can focus on higher-level concerns

### Typical usage 
```jsx
<Button
  disabled={false}
  icon="gear"
  onClick={this.clickHandler}
  size="large"
  title="Engage"
  type="flat"  
/>
```

### Complete props
```js
Button.propTypes = {
  disabled: PropTypes.bool
  icon: PropTypes.oneOf(Button.hig.ICONS),
  link: PropTypes.string,
  onBlur: PropTypes.func,
  onClick: PropTypes.func,
  onFocus: PropTypes.func,
  onHover: PropTypes.func,
  size: PropTypes.oneOf(Button.hig.SIZES),
  title: PropTypes.string,
  type: PropTypes.oneOf(Button.hig.TYPES)
}
```

---

**TODO**
- [x] Add PropTypes
- [x] Add docgenInfo
- [ ] Add unit test coverage
- [x] Add to playground
- [x] Add to storybook
  - [x] With code sample
  - [x] With props table
- [x] Canary build on NPM

**Comment by aneyzberg** [comment]
competed by #286 
canary build 1.0.3-alpha.7dd23f72

**Comment by camwest** [comment]
@aneyzberg 

When I click on "Show Info" here - https://cdn.web-platform.io/orion-ui/orion/snapshot-master/react-hig/storybook/index.html?knob-Size=large&knob-Type=flat&knob-Disabled=false&knob-Instructions=&knob-Label=My%20text%20field&knob-Name=my-text-field&knob-Placeholder=Tell%20me%20how%20you%20really%20feel&knob-Required=&selectedKind=Button&selectedStory=Standard%20Button&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs

It says "No propTypes defined" any idea why the prop types aren't showing up?

**Comment by aneyzberg** [comment]
@camwest let me take a look
