### ISSUE TITLE
Add Checkbox

### ISSUE THREAD

**Issue by nfiniteset** [Autodesk/orion-ui#282]
```
As a developer
I want to add checkboxes to my application
So that my users are able to interact with the application
```

### Typical usage 
```jsx
<Checkbox
  disabled={false}
  onChange={this.handleCheckboxChange}
/>
```

### Complete props
```js
Checkbox.propTypes = {
  name: PropTypes.string,
  value: PropTypes.bool,
  label: PropTypes.string,
  checked: PropTypes.bool,
  required: PropTypes.string
  disabled: PropTypes.bool,
  onBlur: PropTypes.func,
  onChange: PropTypes.func,
  onFocus: PropTypes.func,
}
```

---

**TODO**
- [x] Add PropTypes
- [x] Add docgenInfo
- [x] Add unit test coverage
- [x] Add to playground
- [x] Add to storybook
  - [x] With code sample
  - [x] With props table
- [x] Canary build on NPM

**Comment by nfiniteset** [comment]
```
As a developer
I want to add checkboxes to my application
So that our users are able to interact with our application
```

### Typical usage 
```jsx
<Checkbox
  disabled={false}
  onChange={this.clickHandler}
/>
```

### Complete props
```js
Button.propTypes = {
  name: PropTypes.string,
  value: PropTypes.bool,
  label: PropTypes.string,
  checked: PropTypes.bool,
  required: PropTypes.string
  disabled: PropTypes.bool,
  onFocus: PropTypes.func,
  onFocus: PropTypes.func,
}
```

---

**TODO**
- [ ] Add PropTypes
- [ ] Add docgenInfo
- [ ] Add unit test coverage
- [ ] Add to playground
- [ ] Add to storybook
  - [ ] With code sample
  - [ ] With props table
- [ ] Canary build on NPM

**Comment by shannonwells** [comment]
Canary build:  - react-playground: 1.0.3 => 1.0.3-alpha.c35929b8 (private)

Merge: https://circleci.com/gh/Autodesk/orion-ui/1418
