### ISSUE TITLE
February Iteration Plan

### ISSUE THREAD

**Issue by camwest** [Autodesk/orion-ui#56]
# Plan Items

## Themes

* datepicker, polish, and wrap-up

### Button Component

* [x] Angular adapter for Button https://github.com/orion-ui/orion/issues/34

### Select Menu Component

* [x] Open & Close Menu https://github.com/orion-ui/orion/issues/45
* [x] Navigate & Select Options https://github.com/orion-ui/orion/issues/46
* [x] Viewport Scrolling https://github.com/orion-ui/orion/issues/90
* [x] Disabled Menu & Options https://github.com/orion-ui/orion/issues/47
* [x] Searchable https://github.com/orion-ui/orion/issues/49
* [ ] Clearing Options https://github.com/orion-ui/orion/issues/48

### Date Picker Component

* [x] Create specs for datepicker https://github.com/orion-ui/orion/issues/65
* [x] Focus & Render Calendar https://github.com/orion-ui/orion/issues/73
* [x] Navigation & Selection https://github.com/orion-ui/orion/issues/74
* [x] Custom Formatting https://github.com/orion-ui/orion/issues/75
* [ ] Clearable Dates https://github.com/orion-ui/orion/issues/76 
* [ ] Custom Disabled Dates https://github.com/orion-ui/orion/issues/77

## Engineering

* [x] Setup S3 and CloudFront for snapshots https://github.com/orion-ui/orion/issues/16
* [ ] Visual regression testing should run against Safari https://github.com/orion-ui/orion/issues/172

## Documentation

* [x] Landing Page https://github.com/orion-ui/orion/issues/79
* [ ] Sample Application https://github.com/orion-ui/orion/issues/80
* [ ] Create Redux Sample Application https://github.com/orion-ui/orion/issues/173
* [ ] API docs wireframes
* [ ] Button API docs
* [ ] Select API docs
* [ ] Datepicker API docs
* Announcement blog post
* Make sure README.md from the root gets copied when each package is published

## New Bugs

* [x] Focus is not visually distinct in Firefox https://github.com/orion-ui/orion/issues/87
* [x] Keyboard interactions do not work on Select in Safari 10 https://github.com/orion-ui/orion/issues/88
* [x] Components are broken Angular Playground in Safari 10 and Firefox 51 https://github.com/orion-ui/orion/issues/89
* [x] Keyboard navigation should not scroll the page https://github.com/orion-ui/orion/issues/93
* [x] Select menu does not open in Safari/Angular Playground https://github.com/orion-ui/orion/issues/97
* [x] Select shows up twice when created inside an ngRepeat https://github.com/orion-ui/orion/issues/98
* [x] Select popover does not track select base when select moves on the page https://github.com/orion-ui/orion/issues/108
* [x] Cannot tab past select menu https://github.com/orion-ui/orion/issues/111
* [x] Tabbing twice into select on react-playground causes the option to be de-selected https://github.com/orion-ui/orion/issues/110
* [x] Selecting menu option requires clicking twice https://github.com/orion-ui/orion/issues/112
* [x] Select menu option cannot be selected  https://github.com/orion-ui/orion/issues/117
* [x] WCT tests do not fail CI when they fail https://github.com/orion-ui/orion/issues/107
* [x] Clicking text in closed, unfocused select does not open menu https://github.com/orion-ui/orion/issues/122
* [x] Microsoft Edge: Keyboard events not working https://github.com/orion-ui/orion/issues/123
* [x] Choosing an option with the mouse does not work in Firefox and Edge https://github.com/orion-ui/orion/issues/124
* [x] WCT Test Error - TypeError: Cannot read property 'decl' of undefined https://github.com/orion-ui/orion/issues/133
* [x] An open select menu should always appear on top https://github.com/orion-ui/orion/issues/135
* [x] Select popover is positioned incorrectly the first time in Safari https://github.com/orion-ui/orion/issues/136
* [x] Date picker input should not be directly editable https://github.com/orion-ui/orion/issues/137
* [x] ESC should focus out the date picker https://github.com/orion-ui/orion/issues/138
* [x] Opening select menu causes rendering jank https://github.com/orion-ui/orion/issues/120
* [x] Button text should not be selectable https://github.com/orion-ui/orion/issues/121
* [x] Hovering disabled option should not remove focus from previous option  https://github.com/orion-ui/orion/issues/148
* [x] Selecting a date twice results in an invalid date  https://github.com/orion-ui/orion/issues/149
* [x] MS Edge shows input clear button which puts datepicker into a weird state  https://github.com/orion-ui/orion/issues/150
* [x] Implement Angular Datepicker API https://github.com/orion-ui/orion/issues/151
* [ ] Angular source examples in storybook are out of date https://github.com/orion-ui/orion/issues/157
* [x] Current date is not selectable with custom disabled date https://github.com/orion-ui/orion/issues/162
* [x] Placeholder does not disappear after selection in Safari https://github.com/orion-ui/orion/issues/163
* [x] When a date set is set as a property all other dates should not be disabled https://github.com/orion-ui/orion/issues/164
* [x] Safari placeholder disappears on searchable select https://github.com/orion-ui/orion/issues/165
* [x] Edge shows horizontal scrollbars when rendering options in select https://github.com/orion-ui/orion/issues/166
* [ ] Clearable date picker does not work in angular https://github.com/orion-ui/orion/issues/180
* [ ] ESC should not clear select when clearable=false https://github.com/orion-ui/orion/issues/181
* [ ] Select Menu clearable should not override selectedIndex property  https://github.com/orion-ui/orion/issues/182

## New Tech Debt

* [x] Storybook source viewer should remember React vs Angular - https://github.com/orion-ui/orion/issues/86
* [ ] Organize public API https://github.com/orion-ui/orion/issues/106
* [ ] Custom-Elements-Polyfill is copy & pasted throughout codebase - https://github.com/orion-ui/orion/issues/94
* [ ] Move state application from react and angular wrappers into the web component layer https://github.com/orion-ui/orion/issues/167
* [ ] Dry up getter / setters in web components https://github.com/orion-ui/orion/issues/168
* [ ] Refactor react wrappers into a single component https://github.com/orion-ui/orion/issues/169

## Developer Workflow

* We need a Top Level Compile Watcher - https://github.com/orion-ui/orion/issues/82
* [ ] Write "minute-to-minute" developer workflow guide https://github.com/orion-ui/orion/issues/170
* [ ] Write a high level architecture guide https://github.com/orion-ui/orion/issues/171
