### ISSUE TITLE
Datepicker Roadmap

### ISSUE THREAD

**Issue by camwest** [Autodesk/orion-ui#84]
### Trello

<img width="299" alt="screenshot 2017-01-31 08 43 00" src="https://cloud.githubusercontent.com/assets/22905/22474689/77df641a-e791-11e6-8a90-2bc96f19e60a.png">

Missing Capabilities:

* [ ] Change the month or year via a select menu
* [ ] Layout the calendar and the input separately instead of using a popover 

### Mac OS Datepicker

<img width="175" alt="screenshot 2017-02-01 07 59 12" src="https://cloud.githubusercontent.com/assets/22905/22514785/4ae335ee-e855-11e6-9f95-bc7776cc5728.png">

Missing Capabilities:

* [ ] Change the date via a structured input (left and right arrow keys move between d/m/y)

### Blueprint Datepicker

![screenshot 2017-02-14 09 49 52](https://cloud.githubusercontent.com/assets/22905/22941605/0223f780-f29b-11e6-8bbd-d9ab5a869366.png)

* [ ] Change the month or year via a select menu
